channels:
  - fierromechanics
  - conda-forge

dependencies:
  - black
  - boa
  - calculix
  - ccx2paraview >=3.2
  - fierro-fe-cpu
  # Remove trilinos-cpu explicit requirement when Fierro package(s) resolve the missing library issue
  # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/865
  - trilinos-cpu <=15
  - flake8
  - glab >=1.52
  - h5netcdf
  - h5py
  - ipython
  - lazy_loader >=0.4
  - matplotlib-base
  - meshio
  - mypy
  - networkx
  # Required to satisfy undocumented SALib dependencies on numpy version
  - numpy >=2
  - pandas
  - pip
  - pytest >=6
  - pytest-cov
  - pytest-xdist
  - python-build
  - python-gmsh
  - pyyaml
  # Required to satisfy undocumented SALib dependencies on numpy version
  - salib >=1.5.1
  - scipy >=1
  - scons >=4.6
  - seaborn
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinxcontrib-bibtex
  - twine >=5
  # Remove explicit dependency on VTK and rely on ccx2paraview when a VTK >=9.4 version fixes the macOS crash
  # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/901
  - vtk <=9.3
  - xarray >=2024.10.0
