channels:
  - conda-forge

dependencies:
  - black
  - boa
  - calculix
  - ccx2paraview >=3.2
  - flake8
  - h5netcdf
  - h5py
  - matplotlib-base
  - meshio
  - mypy
  - networkx
  # Required to satisfy undocumented SALib dependencies on numpy version
  - numpy >=2
  - pandas
  - pip
  - pytest >=6
  - pytest-cov
  - pytest-xdist
  - python-build
  - python-gmsh
  - pyyaml
  # Required to satisfy undocumented SALib dependencies on numpy version
  - salib >=1.5.1
  - scipy >=1
  - scons >=4.6
  - seaborn
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinxcontrib-bibtex
  - xarray >=2024.10.0
