channels:
  - conda-forge

dependencies:
  - matplotlib
  - pandas
  - pyyaml
  - scons >=4
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - waves
  - xarray
